version: 2
updates:
  - package-ecosystem: "maven"
    open-pull-requests-limit: 10
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    groups:
      minor-and-patch-version-updates:
        update-types:
        - "minor"
        - "patch"
