name: Release

on:
  push:
    branches:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set up Maven cache
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run Maven
        run: TZ=Europe/Berlin xvfb-run mvn clean verify
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: target/*.zip
      - name: Collect release metadata
        id: collect_release_metadata
        run: |
          echo "release_timestamp=$(date '+%Y-%m-%d @ %H:%M')" >> $GITHUB_ENV
          echo "release_timestamp_terse=$(date '+%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
          echo "release_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "release_file=$(ls target/bibleserver-scraper-*.jar)" >> $GITHUB_ENV
          echo "release_file_short=$(ls target/bibleserver-scraper-*.jar | sed -e 's#^.*/##g')" >> $GITHUB_ENV
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ env.release_timestamp_terse }}-${{ env.release_hash }}
          release_name: Release ${{ env.release_timestamp }}
          body: built from commit ${{ env.release_hash }}
      - name: Upload release artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.release_file }}
          asset_name: ${{ env.release_file_short }}
          asset_content_type: application/java-archive
