name: Build

on:
  push:
    branches:
      - "**"

jobs:
  release:
    uses: mathisdt/workflows/.github/workflows/maven.yaml@master
    with:
      pattern-to-release: bibleserver-scraper-*.jar
    secrets: inherit
